services:
    devnet:
        # Use the devnet image with predeployed contracts
        image: ghcr.io/vepaks/go-ethereum_devnet:master-latest
        pull_policy: always
        ports:
            - "8545:8545" # HTTP JSON-RPC
            - "8546:8546" # WebSocket
            - "30303:30303" # P2P communication
            - "30303:30303/udp" # P2P discovery
        volumes:
            - devnet-data:/root/.ethereum
            - ../../hardhat:/app:ro
        environment:
            - GETH_ARGS=--dev --http --http.addr 0.0.0.0 --http.port 8545 --http.api eth,net,web3,debug,miner --http.corsdomain '*' --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.api eth,net,web3,debug,miner --ws.origins '*' --allow-insecure-unlock --rpc.allow-unprotected-txs --nodiscover --miner.gaslimit ${GAS_LIMIT:-11500000} --miner.gasprice ${GAS_PRICE:-1000000}
        env_file:
            - ./.env.template
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "-f",
                    "-X",
                    "POST",
                    "-H",
                    "Content-Type: application/json",
                    "--data",
                    '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}',
                    "http://localhost:8545",
                ]
            interval: 5s
            timeout: 3s
            retries: 10
            start_period: 10s

    hardhat-tests:
        image: node:18-alpine
        depends_on:
            devnet:
                condition: service_healthy
        working_dir: /app
        volumes:
            - ../../hardhat:/app
        command: >
            sh -c "cd /app &&
                   npm install &&
                   npx hardhat test --network localhost"
        environment:
            - HARDHAT_NETWORK=localhost
            - HARDHAT_NETWORK_URL=http://devnet:8545
        env_file:
            - ./.env.template

volumes:
    devnet-data:
        name: go-ethereum-devnet-data
