name: Deploy Devnet

on:
  pull_request:
    types: [closed]
    branches:
      - master
      - develop

jobs:
  build-and-push-devnet:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Deploy')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment based on target branch
        id: set-env
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "master" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          elif [[ "${{ github.event.pull_request.base.ref }}" == "develop" ]]; then
            echo "ENVIRONMENT=stage" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for devnet image
        id: meta-devnet
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}_devnet
          tags: |
            type=raw,value=${{ github.event.pull_request.base.ref }}_latest
            type=sha,prefix=${{ github.event.pull_request.base.ref }}_,format=short

      - name: Build and push devnet Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./ci/hardhat
          file: ./ci/hardhat/Dockerfile.devnet
          push: true
          tags: ${{ steps.meta-devnet.outputs.tags }}
          labels: |
            org.opencontainers.image.title=go-ethereum_devnet
            org.opencontainers.image.description=go-ethereum devnet image with Hardhat integration | Branch: ${{ github.event.pull_request.base.ref }} | Environment: ${{ env.ENVIRONMENT }} | Build: ${{ github.run_number }} | Commit: ${{ github.sha }}
            org.opencontainers.image.version=${{ github.sha }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.documentation=${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/README.md
            org.opencontainers.image.authors=${{ github.actor }}
          build-args: |
            COMMIT=${{ github.sha }}
            VERSION=${{ github.sha }}
            BUILDNUM=${{ github.run_number }}
            BRANCH=${{ github.event.pull_request.base.ref }}
            ENVIRONMENT=${{ env.ENVIRONMENT }} 